module.exports = {
  RESULTS: new Set(["SUCCESS", "DENIED", "FAILED"]),
  TARGET_TYPES: new Set([
    "course",
    "course_version",
    "lesson",
    "lesson_content",
    "enrollment",
    "user",
    "session",
    "refresh_token",
    "mfa_trust",
    "assignment",
    "submission",
  ]),
  ENTITY_TYPES: new Set([
    "course",
    "course_version",
    "lesson",
    "lesson_content",
    "enrollment",
    "user",
    "session",
    "refresh_token",
    "mfa_trust",
    "assignment",
    "submission",
  ]),
  CHANGE_TYPES: new Set(["CREATE", "UPDATE", "DELETE", "STATUS_CHANGE"]),
};
